//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address length is too long..
        /// </summary>
        internal static string ADDRESS_LENGTH_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_LENGTH_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name is too long..
        /// </summary>
        internal static string CITY_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("CITY_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is too long..
        /// </summary>
        internal static string COMPANY_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("COMPANY_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name is too long..
        /// </summary>
        internal static string COUNTRY_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("COUNTRY_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be before end date..
        /// </summary>
        internal static string DATE_START_LESS_THAN_END {
            get {
                return ResourceManager.GetString("DATE_START_LESS_THAN_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not be empty..
        /// </summary>
        internal static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with our email service. Please try again later..
        /// </summary>
        internal static string EMAIL_SEND_FAILED {
            get {
                return ResourceManager.GetString("EMAIL_SEND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax length is too long..
        /// </summary>
        internal static string FAX_LENGTH_TOO_LONG {
            get {
                return ResourceManager.GetString("FAX_LENGTH_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not found..
        /// </summary>
        internal static string GROUP_NOT_FOUND {
            get {
                return ResourceManager.GetString("GROUP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request body..
        /// </summary>
        internal static string INVALID_BODY {
            get {
                return ResourceManager.GetString("INVALID_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid validation key..
        /// </summary>
        internal static string INVALID_KEY {
            get {
                return ResourceManager.GetString("INVALID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        internal static string INVALID_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid/missing lead name..
        /// </summary>
        internal static string LEAD_NAME_INVALID {
            get {
                return ResourceManager.GetString("LEAD_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not be empty..
        /// </summary>
        internal static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files received..
        /// </summary>
        internal static string NO_FILES_FOUND {
            get {
                return ResourceManager.GetString("NO_FILES_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images in these formats are allowed: &quot;.jpeg&quot;, &quot;.jpg&quot;, &quot;png&quot;, &quot;.tif&quot;, &quot;.tiff&quot;.
        /// </summary>
        internal static string NOT_IMAGE {
            get {
                return ResourceManager.GetString("NOT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note&apos;s body is empty..
        /// </summary>
        internal static string NOTE_EMPTY {
            get {
                return ResourceManager.GetString("NOTE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone length is too long..
        /// </summary>
        internal static string PHONE_LENGTH_TOO_LONG {
            get {
                return ResourceManager.GetString("PHONE_LENGTH_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype name is too long..
        /// </summary>
        internal static string SKYPE_TOO_LONG {
            get {
                return ResourceManager.GetString("SKYPE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something bad happened..
        /// </summary>
        internal static string SOMETHING_WRONG {
            get {
                return ResourceManager.GetString("SOMETHING_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must not be empty..
        /// </summary>
        internal static string TITLE_EMPTY {
            get {
                return ResourceManager.GetString("TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token has expired..
        /// </summary>
        internal static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        internal static string TOKEN_INVALID {
            get {
                return ResourceManager.GetString("TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authenticated, please try again..
        /// </summary>
        internal static string UNAUTHENTICATED {
            get {
                return ResourceManager.GetString("UNAUTHENTICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource..
        /// </summary>
        internal static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website name is too long..
        /// </summary>
        internal static string WEBSITE_TOO_LONG {
            get {
                return ResourceManager.GetString("WEBSITE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Password is incorrect..
        /// </summary>
        internal static string WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_PASSWORD", resourceCulture);
            }
        }
    }
}
