//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend.Resources.SuccessMessages", typeof(SuccessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar successfully changed..
        /// </summary>
        internal static string AVATAR_CHANGED {
            get {
                return ResourceManager.GetString("AVATAR_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call successfully created..
        /// </summary>
        internal static string CALL_CREATED {
            get {
                return ResourceManager.GetString("CALL_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call successfully deleted..
        /// </summary>
        internal static string CALL_DELETED {
            get {
                return ResourceManager.GetString("CALL_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call successfully updated..
        /// </summary>
        internal static string CALL_MODIFIED {
            get {
                return ResourceManager.GetString("CALL_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign successfully created..
        /// </summary>
        internal static string CAMPAIGN_CREATED {
            get {
                return ResourceManager.GetString("CAMPAIGN_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign successfully deleted..
        /// </summary>
        internal static string CAMPAIGN_DELETED {
            get {
                return ResourceManager.GetString("CAMPAIGN_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign successfully updated..
        /// </summary>
        internal static string CAMPAIGN_MODIFIED {
            get {
                return ResourceManager.GetString("CAMPAIGN_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact successfully added..
        /// </summary>
        internal static string CONTACT_ADDED {
            get {
                return ResourceManager.GetString("CONTACT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact successfully removed..
        /// </summary>
        internal static string CONTACT_REMOVED {
            get {
                return ResourceManager.GetString("CONTACT_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group successfully created..
        /// </summary>
        internal static string GROUP_CREATED {
            get {
                return ResourceManager.GetString("GROUP_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group successfully deleted..
        /// </summary>
        internal static string GROUP_DELETED {
            get {
                return ResourceManager.GetString("GROUP_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group successfully updated..
        /// </summary>
        internal static string GROUP_MODIFIED {
            get {
                return ResourceManager.GetString("GROUP_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead successfully added..
        /// </summary>
        internal static string LEAD_ADDED {
            get {
                return ResourceManager.GetString("LEAD_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead successfully created..
        /// </summary>
        internal static string LEAD_CREATED {
            get {
                return ResourceManager.GetString("LEAD_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead successfully deleted..
        /// </summary>
        internal static string LEAD_DELETED {
            get {
                return ResourceManager.GetString("LEAD_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead successfully updated..
        /// </summary>
        internal static string LEAD_MODIFIED {
            get {
                return ResourceManager.GetString("LEAD_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead successfully removed..
        /// </summary>
        internal static string LEAD_REMOVED {
            get {
                return ResourceManager.GetString("LEAD_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting successfully created..
        /// </summary>
        internal static string MEETING_CREATED {
            get {
                return ResourceManager.GetString("MEETING_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting successfully deleted..
        /// </summary>
        internal static string MEETING_DELETED {
            get {
                return ResourceManager.GetString("MEETING_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note added..
        /// </summary>
        internal static string NOTE_ADDED {
            get {
                return ResourceManager.GetString("NOTE_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note successfully deleted..
        /// </summary>
        internal static string NOTE_DELETED {
            get {
                return ResourceManager.GetString("NOTE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed..
        /// </summary>
        internal static string PASSWORD_CHANGED {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset..
        /// </summary>
        internal static string PASSWORD_RESET {
            get {
                return ResourceManager.GetString("PASSWORD_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag successfully added..
        /// </summary>
        internal static string TAG_ADDED {
            get {
                return ResourceManager.GetString("TAG_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag successfully removed from this item..
        /// </summary>
        internal static string TAG_REMOVED {
            get {
                return ResourceManager.GetString("TAG_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created..
        /// </summary>
        internal static string USER_CREATED {
            get {
                return ResourceManager.GetString("USER_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deleted..
        /// </summary>
        internal static string USER_DELETED {
            get {
                return ResourceManager.GetString("USER_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully updated..
        /// </summary>
        internal static string USER_MODIFIED {
            get {
                return ResourceManager.GetString("USER_MODIFIED", resourceCulture);
            }
        }
    }
}
