

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='USER' and xtype='U')
BEGIN
    CREATE TABLE [USER] (
        ID int primary key identity(1,1),
		FirstName nvarchar(50) not null,
		Avatar nvarchar(500),
		LastName nvarchar(50) not null,
		Username varchar(30) not null,
		Hash varchar(200),
		RememberMeToken varchar(200),
		Email nvarchar(320) not null,
		Phone varchar(15),
		Skype nvarchar(32),
		CreatedAt datetime,
		CreatedBy int,
		GROUP_ID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='LEAD' and xtype='U')
BEGIN
    CREATE TABLE [LEAD] (
        ID int primary key identity(1,1),
		Name nvarchar(100) not null,
		Email nvarchar(320) not null,
		LeadSource int,
		AnnualRevenue bigint,
		CompanyName nvarchar(150),
		Fax varchar(15),
		Description nvarchar(2000),
		INDUSTRY_ID int,
		NoEmail bit default 0,
		LeadOwner int,
		NoCall bit default 0,
		Phone varchar(15),
		Website nvarchar(100),
		Avatar nvarchar(500),
		Skype nvarchar(32),
		CreatedAt datetime,
		CreatedBy int,
		ModifiedAt datetime,
		ModifiedBy int,
		PRIORITY_ID int,
		Country nvarchar(100),
		City nvarchar(100),
		AddressDetail nvarchar(200)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='LEAD_SOURCE' and xtype='U')
BEGIN
    CREATE TABLE [LEAD_SOURCE] (
        ID int primary key identity(1,1),
		Name nvarchar(100) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='INDUSTRY' and xtype='U')
BEGIN
    CREATE TABLE [INDUSTRY] (
        ID int primary key identity(1,1),
		Name nvarchar(100) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='LEAD_STATUS' and xtype='U')
BEGIN
    CREATE TABLE [LEAD_STATUS] (
        ID int primary key identity(1,1),
		Name nvarchar(50) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ACCOUNT_TYPE' and xtype='U')
BEGIN
    CREATE TABLE [ACCOUNT_TYPE] (
        ID int primary key identity(1,1),
		Name nvarchar(20) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PRIORITY' and xtype='U')
BEGIN
    CREATE TABLE [PRIORITY] (
        ID int primary key identity(1,1),
		Name nvarchar(10) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TASK_STATUS' and xtype='U')
BEGIN
    CREATE TABLE [TASK_STATUS] (
        ID int primary key identity(1,1),
		Name nvarchar(20) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CALL_RESULT' and xtype='U')
BEGIN
    CREATE TABLE [CALL_RESULT] (
        ID int primary key identity(1,1),
		Name nvarchar(40) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CALL_REASON' and xtype='U')
BEGIN
    CREATE TABLE [CALL_REASON] (
        ID int primary key identity(1,1),
		Name nvarchar(20) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CALL_TYPE' and xtype='U')
BEGIN
    CREATE TABLE [CALL_TYPE] (
        ID int primary key identity(1,1),
		Name nvarchar(20) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CAMPAIGN_TYPE' and xtype='U')
BEGIN
    CREATE TABLE [CAMPAIGN_TYPE] (
        ID int primary key identity(1,1),
		Name nvarchar(30) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CAMPAIGN_STATUS' and xtype='U')
BEGIN
    CREATE TABLE [CAMPAIGN_STATUS] (
        ID int primary key identity(1,1),
		Name nvarchar(20) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CAMPAIGN_TARGET' and xtype='U')
BEGIN
    CREATE TABLE [CAMPAIGN_TARGET] (
        ID int primary key identity(1,1),
		CAMPAIGN_ID int,
		CONTACT_ID int,
		LEAD_ID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TAG' and xtype='U')
BEGIN
    CREATE TABLE [TAG] (
        ID int primary key identity(1,1),
		Name nvarchar(20) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='LOST_REASON' and xtype='U')
BEGIN
    CREATE TABLE [LOST_REASON] (
        ID int primary key identity(1,1),
		Reason nvarchar(100) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='GROUP' and xtype='U')
BEGIN
    CREATE TABLE [GROUP] (
        ID int primary key identity(1,1),
		Name nvarchar(50) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='GROUP_PERMISSION' and xtype='U')
BEGIN
    CREATE TABLE [GROUP_PERMISSION] (
        GROUP_ID int,
		PERMISSION_ID int,
		PRIMARY KEY(GROUP_ID, PERMISSION_ID)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PERMISSION' and xtype='U')
BEGIN
    CREATE TABLE [PERMISSION] (
        ID int primary key identity(1,1),
		Name nvarchar(50) not null,
		Description nvarchar(100),
		PERMISSION_ORDER_ID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PERMISSION_ORDER' and xtype='U')
BEGIN
    CREATE TABLE [PERMISSION_ORDER] (
        ID int primary key identity(1,1),
		Name nvarchar(50) not null
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CAMPAIGN' and xtype='U')
BEGIN
    CREATE TABLE [CAMPAIGN] (
        ID int primary key identity(1,1),
		Name nvarchar(100) not null,
		Description nvarchar(2000),
		CampaignOwner int,
		StartDate datetime,
		EndDate datetime,
		ActualCost bigint,
		BudgetedCost bigint,
		ExpectedResponse int,
		ExpectedRevenue bigint,
		NumberSent int,
		CreatedAt datetime,
		CreatedBy int,
		ModifiedBy int,
		ModifiedAt datetime,
		CAMPAIGN_TYPE_ID int,
		CAMPAIGN_STATUS_ID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='COMPETITOR' and xtype='U')
BEGIN
    CREATE TABLE [COMPETITOR] (
        ID int primary key identity(1,1),
		Name nvarchar(100) not null,
		Website nvarchar(100),
		Strengths nvarchar(2000),
		Weaknesses nvarchar(2000)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='STAGE' and xtype='U')
BEGIN
    CREATE TABLE [STAGE] (
        ID int primary key identity(1,1),
		Name nvarchar(30) not null,
		Probability int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='DEAL' and xtype='U')
BEGIN
    CREATE TABLE [DEAL] (
        ID int primary key identity(1,1),
		Name nvarchar(100) not null,
		ClosingDate datetime,
		DealOwner int,
		Amount bigint,
		ExpectedRevenue bigint,
		Contact_ID int,
		ACCOUNT_ID int,
		CAMPAIGN_ID int,
		isLost bit default 0,
		LOST_REASON_ID int,
		Description nvarchar(2000),
		ModifiedBy int,
		ModifiedAt datetime,
		CreatedBy int,
		CreatedAt datetime,
		PRIORITY_ID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='STAGE_HISTORY' and xtype='U')
BEGIN
    CREATE TABLE [STAGE_HISTORY] (
        STAGE_ID int,
		DEAL_ID int,
		ModifiedBy int,
		ModifiedAt datetime,
		PRIMARY KEY(STAGE_ID, DEAL_ID)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='DEAL_COMPETITOR' and xtype='U')
BEGIN
    CREATE TABLE [DEAL_COMPETITOR] (
        COMPETITOR_ID int,
		DEAL_ID int,
		Suggestions nvarchar(2000),
		ThreatLevel nvarchar(20),
		PRIMARY KEY(COMPETITOR_ID, DEAL_ID)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TAG_ITEM' and xtype='U')
BEGIN
    CREATE TABLE [TAG_ITEM] (
        ID int primary key identity(1,1),
		TAG_ID int not null,
		DEAL_ID int,
		CALL_ID int,
		TASK_ID int, 
		MEETING_ID int,
		CAMPAIGN_ID int,
		LEAD_ID int,
		ACCOUNT_ID int,
		CONTACT_ID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='NOTE' and xtype='U')
BEGIN
    CREATE TABLE [NOTE] (
        ID int primary key identity(1,1),
		CreatedBy int not null,
		CreatedAt datetime,
		NoteBody nvarchar(2000),
		ACCOUNT_ID int,
		CONTACT_ID int,
		LEAD_ID int,
		DEAL_ID int,
		TASK_TEMPLATE_ID int,
		CAMPAIGN_ID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='FILE' and xtype='U')
BEGIN
    CREATE TABLE [FILE] (
        ID int primary key identity(1,1),
		FileName nvarchar(200),
		FileSize int,
		NOTE_ID int,
		Data varbinary(max),
		FileStorePath nvarchar(500)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ACCOUNT' and xtype='U')
BEGIN
    CREATE TABLE [ACCOUNT] (
        ID int primary key identity(1,1),
		AccountOwner int,
		AccountCollaborator int,
		Name nvarchar(100),
		Phone varchar(15),
		Fax varchar(15),
		Website nvarchar(100),
		ACCOUNT_TYPE_ID int,
		INDUSTRY_ID int,
		TaxCode nvarchar(30),
		NoEmployees int,
		AnnualRevenue bigint,
		BankName varchar(100),
		BankAccountName nvarchar(100),
		BankAccount varchar(100),
		Avatar nvarchar(500),
		Email nvarchar(320),	
		CreatedAt datetime,
		CreatedBy int,
		ConvertFrom int,
		ModifiedBy int,
		ModifiedAt datetime,
		Country nvarchar(100),
		City nvarchar(100),
		AddressDetail nvarchar(200)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CONTACT' and xtype='U')
BEGIN
    CREATE TABLE [CONTACT] (
        ID int primary key identity(1,1),
		ContactOwner int,
		ContactCollaborator int,
		Name nvarchar(100),
		Email nvarchar(320),
		Phone varchar(15),
		Skype nvarchar(32),
		Mobile varchar(15),
		DepartmentName nvarchar(100),
		Birthday date,
		AssistantName nvarchar(100),
		AssistantPhone varchar(15),
		NoEmail bit default 0,
		NoCall bit default 0,		
		CreatedAt datetime,
		CreatedBy int,
		ConvertFrom int,
		ModifiedBy int,
		ModifiedAt datetime,
		PRIORITY_ID int,
		ACCOUNT_ID int,
		Country nvarchar(100),
		City nvarchar(100),
		AddressDetail nvarchar(200)
    )
END
GO


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TASK' and xtype='U')
BEGIN
    CREATE TABLE [TASK] (
        ID int primary key identity(1,1),
		TASK_TEMPLATE_ID int,
		TaskOwner int,
		CONTACT_ID int,
		LEAD_ID int,
		RELATED_CAMPAIGN int,
		RELATED_DEAL int,
		RELATED_ACCOUNT int,
		EndOn datetime
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TASK_TEMPLATE' and xtype='U')
BEGIN
    CREATE TABLE [TASK_TEMPLATE] (
        ID int primary key identity(1,1),
		Title nvarchar(100),
		IsRepeat bit default 0,
		RRule nvarchar(100),
		TASK_STATUS_ID int,
		Description nvarchar(2000),
		CreatedBy int, 
		CreatedAt datetime,
		ModifiedBy int,
		ModifiedAt datetime,
		PRIORITY_ID int,
		IsCompleted bit default 0,
		DueDate datetime
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CALL' and xtype='U')
BEGIN
    CREATE TABLE [CALL] (
        ID int primary key identity(1,1),
		TASK_TEMPLATE_ID int,
		CALLREASON_ID int,
		CALLRESULT_ID int,
		CALLTYPE_ID int,
		Length int,
		CONTACT_ID int,
		LEAD_ID int,
		RELATED_DEAL int,
		RELATED_ACCOUNT int,
		RELATED_CAMPAIGN int,
		StartTime datetime,
		CallOwner int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='MEETING' and xtype='U')
BEGIN
    CREATE TABLE [MEETING] (
        ID int primary key identity(1,1),
		TASK_TEMPLATE_ID int,
		Host int,
		Location nvarchar(200),
		FromDate datetime,
		ToDate datetime,
		IsAllDay bit default 0,
		IsRemindParticipant bit default 0
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='MEETING_PARTICIPANT' and xtype='U')
BEGIN
    CREATE TABLE [MEETING_PARTICIPANT] (
        ID int primary key identity(1,1),
		MEETING_ID int,
		LEAD_ID int,
		USER_ID int,
		CONTACT_ID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='NOTIFICATION' and xtype='U')
BEGIN
    CREATE TABLE [NOTIFICATION] (
        ID int primary key identity(1,1),
		NotificationTitle nvarchar(50),
		NotificationContent nvarchar(100),
		CreatedAt datetime,
		Module nvarchar(20),
		ModuleObjectID int,
		Submodule nvarchar(20),
		SubmoduleObjectID int
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='USER_NOTIFICATION' and xtype='U')
BEGIN
    CREATE TABLE [USER_NOTIFICATION] (
		USER_ID int,
		NOTIFICATION_ID int,
		IsRead bit default 0
		PRIMARY KEY(USER_ID, NOTIFICATION_ID)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='REFRESH_TOKEN' and xtype='U')
BEGIN
    CREATE TABLE [REFRESH_TOKEN] (
		ID int identity(1,1) primary key,
		Token varchar(100),
		USER_ID int
    )
END
GO

ALTER TABLE [REFRESH_TOKEN]
ADD FOREIGN KEY (USER_ID) REFERENCES [USER](ID) ON DELETE CASCADE

ALTER TABLE [USER_NOTIFICATION]
ADD FOREIGN KEY (NOTIFICATION_ID) REFERENCES [NOTIFICATION](ID) ON DELETE CASCADE

ALTER TABLE [USER_NOTIFICATION]
ADD FOREIGN KEY (USER_ID) REFERENCES [USER](ID) ON DELETE CASCADE;
GO

--- USER ---
ALTER TABLE [USER]
ADD FOREIGN KEY (CreatedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [USER]
ADD FOREIGN KEY (GROUP_ID) REFERENCES [GROUP](ID);
GO
--- LEAD ----
ALTER TABLE [LEAD]
ADD FOREIGN KEY (LeadSource) REFERENCES [LEAD_SOURCE](ID);
GO

ALTER TABLE [LEAD]
ADD FOREIGN KEY (INDUSTRY_ID) REFERENCES [INDUSTRY](ID);
GO

ALTER TABLE [LEAD]
ADD FOREIGN KEY (LeadOwner) REFERENCES [USER](ID);
GO

ALTER TABLE [LEAD]
ADD FOREIGN KEY (ModifiedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [LEAD]
ADD FOREIGN KEY (CreatedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [LEAD]
ADD FOREIGN KEY (PRIORITY_ID) REFERENCES [PRIORITY](ID);
GO
---CAMPAIGN_TARGET---
ALTER TABLE [CAMPAIGN_TARGET]
ADD FOREIGN KEY (CAMPAIGN_ID) REFERENCES [CAMPAIGN](ID) ON DELETE CASCADE;
GO

ALTER TABLE [CAMPAIGN_TARGET]
ADD FOREIGN KEY (CONTACT_ID) REFERENCES [CONTACT](ID) ON DELETE CASCADE;
GO

ALTER TABLE [CAMPAIGN_TARGET]
ADD FOREIGN KEY (LEAD_ID) REFERENCES [LEAD](ID) ON DELETE CASCADE;
GO

---GROUP_PERMISSION---
ALTER TABLE [GROUP_PERMISSION]
ADD FOREIGN KEY (GROUP_ID) REFERENCES [GROUP](ID) ON DELETE CASCADE;
GO

ALTER TABLE [GROUP_PERMISSION]
ADD FOREIGN KEY (PERMISSION_ID) REFERENCES [PERMISSION](ID) ON DELETE CASCADE;
GO

---PERMISSION---
ALTER TABLE [PERMISSION]
ADD FOREIGN KEY (PERMISSION_ORDER_ID) REFERENCES [PERMISSION_ORDER](ID);
GO

---CAMPAIGN---
ALTER TABLE [CAMPAIGN]
ADD FOREIGN KEY (CampaignOwner) REFERENCES [USER](ID);
GO

ALTER TABLE [CAMPAIGN]
ADD FOREIGN KEY (CreatedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [CAMPAIGN]
ADD FOREIGN KEY (ModifiedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [CAMPAIGN]
ADD FOREIGN KEY (CAMPAIGN_TYPE_ID) REFERENCES [CAMPAIGN_TYPE](ID);
GO

ALTER TABLE [CAMPAIGN]
ADD FOREIGN KEY (CAMPAIGN_STATUS_ID) REFERENCES [CAMPAIGN_STATUS](ID);
GO

---DEAL---
ALTER TABLE [DEAL]
ADD FOREIGN KEY (DealOwner) REFERENCES [USER](ID);
GO

ALTER TABLE [DEAL]
ADD FOREIGN KEY (CONTACT_ID) REFERENCES [CONTACT](ID);
GO

ALTER TABLE [DEAL]
ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES [ACCOUNT](ID);
GO

ALTER TABLE [DEAL]
ADD FOREIGN KEY (CAMPAIGN_ID) REFERENCES [CAMPAIGN](ID);
GO

ALTER TABLE [DEAL]
ADD FOREIGN KEY (LOST_REASON_ID) REFERENCES [LOST_REASON](ID);
GO

ALTER TABLE [DEAL]
ADD FOREIGN KEY (ModifiedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [DEAL]
ADD FOREIGN KEY (CreatedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [DEAL]
ADD FOREIGN KEY (PRIORITY_ID) REFERENCES [PRIORITY](ID);
GO

---STAGE_HISTORY---
ALTER TABLE [STAGE_HISTORY]
ADD FOREIGN KEY (STAGE_ID) REFERENCES [STAGE](ID) ON DELETE CASCADE;
GO

ALTER TABLE [STAGE_HISTORY]
ADD FOREIGN KEY (DEAL_ID) REFERENCES [DEAL](ID) ON DELETE CASCADE;
GO

ALTER TABLE [STAGE_HISTORY]
ADD FOREIGN KEY (ModifiedBy) REFERENCES [USER](ID) ON DELETE CASCADE;
GO

--DEAL_COMPETITOR---
ALTER TABLE [DEAL_COMPETITOR]
ADD FOREIGN KEY (COMPETITOR_ID) REFERENCES [COMPETITOR](ID) ON DELETE CASCADE;
GO

ALTER TABLE [DEAL_COMPETITOR]
ADD FOREIGN KEY (DEAL_ID) REFERENCES [DEAL](ID) ON DELETE CASCADE;
GO

---TAG_ITEM---
ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (TAG_ID) REFERENCES [TAG](ID) ON DELETE CASCADE;
GO

ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (DEAL_ID) REFERENCES [DEAL](ID) ON DELETE CASCADE;
GO

ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (CALL_ID) REFERENCES [CALL](ID) ON DELETE CASCADE;
GO

ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (TASK_ID) REFERENCES [TASK](ID) ON DELETE CASCADE;
GO

ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (MEETING_ID) REFERENCES [MEETING](ID) ON DELETE CASCADE;
GO

ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (CAMPAIGN_ID) REFERENCES [CAMPAIGN](ID) ON DELETE CASCADE;
GO

ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (LEAD_ID) REFERENCES [LEAD](ID) ON DELETE CASCADE;
GO

ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES [ACCOUNT](ID) ON DELETE CASCADE;
GO

ALTER TABLE [TAG_ITEM]
ADD FOREIGN KEY (CONTACT_ID) REFERENCES [CONTACT](ID) ON DELETE CASCADE;
GO

---NOTE---

ALTER TABLE [NOTE]
ADD FOREIGN KEY (CreatedBy) REFERENCES [USER](ID) ON DELETE CASCADE;
GO

ALTER TABLE [NOTE]
ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES [ACCOUNT](ID) ON DELETE CASCADE;
GO

ALTER TABLE [NOTE]
ADD FOREIGN KEY (CONTACT_ID) REFERENCES [CONTACT](ID) ON DELETE CASCADE;
GO

ALTER TABLE [NOTE]
ADD FOREIGN KEY (LEAD_ID) REFERENCES [LEAD](ID) ON DELETE CASCADE;
GO

ALTER TABLE [NOTE]
ADD FOREIGN KEY (DEAL_ID) REFERENCES [DEAL](ID) ON DELETE CASCADE;
GO

ALTER TABLE [NOTE]
ADD FOREIGN KEY (TASK_TEMPLATE_ID) REFERENCES [TASK_TEMPLATE](ID) ON DELETE CASCADE;
GO

ALTER TABLE [NOTE]
ADD FOREIGN KEY (CAMPAIGN_ID) REFERENCES [CAMPAIGN](ID) ON DELETE CASCADE;
GO

---FILE---
ALTER TABLE [FILE]
ADD FOREIGN KEY (NOTE_ID) REFERENCES [NOTE](ID) ON DELETE CASCADE;
GO

---ACCOUNT---
ALTER TABLE [ACCOUNT]
ADD FOREIGN KEY (AccountOwner) REFERENCES [USER](ID);
GO

ALTER TABLE [ACCOUNT]
ADD FOREIGN KEY (AccountCollaborator) REFERENCES [USER](ID);
GO

ALTER TABLE [ACCOUNT]
ADD FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES [ACCOUNT_TYPE](ID);
GO

ALTER TABLE [ACCOUNT]
ADD FOREIGN KEY (INDUSTRY_ID) REFERENCES [INDUSTRY](ID);
GO

ALTER TABLE [ACCOUNT]
ADD FOREIGN KEY (CreatedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [ACCOUNT]
ADD FOREIGN KEY (ConvertFrom) REFERENCES [LEAD](ID);
GO

ALTER TABLE [ACCOUNT]
ADD FOREIGN KEY (ModifiedBy) REFERENCES [USER](ID);
GO

---CONTACT---
ALTER TABLE [CONTACT]
ADD FOREIGN KEY (ContactOwner) REFERENCES [USER](ID);
GO

ALTER TABLE [CONTACT]
ADD FOREIGN KEY (ContactCollaborator) REFERENCES [USER](ID);
GO

ALTER TABLE [CONTACT]
ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES [ACCOUNT](ID);
GO

ALTER TABLE [CONTACT]
ADD FOREIGN KEY (ModifiedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [CONTACT]
ADD FOREIGN KEY (CreatedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [CONTACT]
ADD FOREIGN KEY (PRIORITY_ID) REFERENCES [PRIORITY](ID);
GO


---TASK---
ALTER TABLE [TASK]
ADD FOREIGN KEY (TASK_TEMPLATE_ID) REFERENCES [TASK_TEMPLATE](ID);
GO

ALTER TABLE [TASK]
ADD FOREIGN KEY (TaskOwner) REFERENCES [USER](ID);
GO

ALTER TABLE [TASK]
ADD FOREIGN KEY (CONTACT_ID) REFERENCES [CONTACT](ID);
GO

ALTER TABLE [TASK]
ADD FOREIGN KEY (LEAD_ID) REFERENCES [LEAD](ID);
GO

ALTER TABLE [TASK]
ADD FOREIGN KEY (RELATED_CAMPAIGN) REFERENCES [CAMPAIGN](ID);
GO

ALTER TABLE [TASK]
ADD FOREIGN KEY (RELATED_DEAL) REFERENCES [DEAL](ID);
GO

ALTER TABLE [TASK]
ADD FOREIGN KEY (RELATED_ACCOUNT) REFERENCES [ACCOUNT](ID);
GO

---TASK_TEMPLATE---
ALTER TABLE [TASK_TEMPLATE]
ADD FOREIGN KEY (TASK_STATUS_ID) REFERENCES [TASK_STATUS](ID);
GO

ALTER TABLE [TASK_TEMPLATE]
ADD FOREIGN KEY (CreatedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [TASK_TEMPLATE]
ADD FOREIGN KEY (ModifiedBy) REFERENCES [USER](ID);
GO

ALTER TABLE [TASK_TEMPLATE]
ADD FOREIGN KEY (PRIORITY_ID) REFERENCES [PRIORITY](ID);
GO

---CALL---
ALTER TABLE [CALL]
ADD FOREIGN KEY (TASK_TEMPLATE_ID) REFERENCES [TASK_TEMPLATE](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (CALLREASON_ID) REFERENCES [CALL_REASON](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (CALLRESULT_ID) REFERENCES [CALL_RESULT](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (CALLTYPE_ID) REFERENCES [CALL_TYPE](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (CONTACT_ID) REFERENCES [CONTACT](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (LEAD_ID) REFERENCES [LEAD](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (RELATED_DEAL) REFERENCES [DEAL](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (RELATED_ACCOUNT) REFERENCES [ACCOUNT](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (RELATED_CAMPAIGN) REFERENCES [CAMPAIGN](ID);
GO

ALTER TABLE [CALL]
ADD FOREIGN KEY (CallOwner) REFERENCES [USER](ID);
GO
---MEETING---
ALTER TABLE [MEETING]
ADD FOREIGN KEY (TASK_TEMPLATE_ID) REFERENCES [TASK_TEMPLATE](ID);
GO

ALTER TABLE [MEETING]
ADD FOREIGN KEY (Host) REFERENCES [USER](ID);
GO
---MEETING_PARTICIPANT---
ALTER TABLE [MEETING_PARTICIPANT]
ADD FOREIGN KEY (MEETING_ID) REFERENCES [MEETING](ID) ON DELETE CASCADE;
GO

ALTER TABLE [MEETING_PARTICIPANT]
ADD FOREIGN KEY (LEAD_ID) REFERENCES [LEAD](ID) ON DELETE CASCADE;
GO

ALTER TABLE [MEETING_PARTICIPANT]
ADD FOREIGN KEY (USER_ID) REFERENCES [USER](ID) ON DELETE CASCADE;
GO

ALTER TABLE [MEETING_PARTICIPANT]
ADD FOREIGN KEY (CONTACT_ID) REFERENCES [CONTACT](ID) ON DELETE CASCADE;
GO
---INDEX---

CREATE INDEX IX_USER ON [USER] (FirstName, LastName, Username, Email, CreatedAt, CreatedBy, GROUP_ID)
GO

CREATE INDEX IX_TOKEN ON [REFRESH_TOKEN] (Token)
go

CREATE INDEX IX_LEAD ON [LEAD] (Name, Email, LeadSource, INDUSTRY_ID, LeadOwner, CreatedBy, ModifiedBy)
CREATE INDEX IX_CAMPAIGN_TARGET ON [CAMPAIGN_TARGET] (CAMPAIGN_ID, CONTACT_ID, LEAD_ID)
CREATE INDEX IX_TAG ON [TAG] (Name)
CREATE INDEX IX_GROUP_PERMISSION ON [GROUP_PERMISSION] (GROUP_ID, PERMISSION_ID)
CREATE INDEX IX_PERMISSION ON [PERMISSION] (PERMISSION_ORDER_ID)
CREATE INDEX IX_CAMPAIGN ON [CAMPAIGN] (CampaignOwner, CreatedBy, ModifiedBy, CAMPAIGN_TYPE_ID, CAMPAIGN_STATUS_ID)
CREATE INDEX IX_DEAL ON [DEAL] (Name, DealOwner, CONTACT_ID, ACCOUNT_ID, CAMPAIGN_ID, LOST_REASON_ID, ModifiedBy, CreatedBy, PRIORITY_ID)
CREATE INDEX IX_STAGE_HISTORY ON [STAGE_HISTORY] (STAGE_ID, DEAL_ID, ModifiedBy)
CREATE INDEX IX_DEAL_COMPETITOR ON [DEAL_COMPETITOR] (COMPETITOR_ID, DEAL_ID)
CREATE INDEX IX_TAG_ITEM ON [TAG_ITEM] (TAG_ID, DEAL_ID, CALL_ID, TASK_ID, MEETING_ID, CAMPAIGN_ID, LEAD_ID, ACCOUNT_ID, CONTACT_ID)
CREATE INDEX IX_NOTE ON [NOTE] (CreatedBy, ACCOUNT_ID, CONTACT_ID, LEAD_ID, DEAL_ID, TASK_TEMPLATE_ID, CAMPAIGN_ID)
CREATE INDEX IX_FILE ON [FILE] (FileName, NOTE_ID)
CREATE INDEX IX_ACCOUNT ON [ACCOUNT] (AccountOwner, AccountCollaborator, Name, ACCOUNT_TYPE_ID, INDUSTRY_ID, CreatedBy, ConvertFrom, ModifiedBy)
CREATE INDEX IX_CONTACT ON [CONTACT] (ContactOwner, ContactCollaborator, Name, ACCOUNT_ID, ModifiedBy, CreatedBy, PRIORITY_ID)
CREATE INDEX IX_TASK ON [TASK] (TASK_TEMPLATE_ID, TaskOwner, CONTACT_ID, LEAD_ID, RELATED_CAMPAIGN, RELATED_DEAL, RELATED_ACCOUNT)
CREATE INDEX IX_TASK_TEMPLATE ON [TASK_TEMPLATE] (TASK_STATUS_ID, CreatedBy, ModifiedBy, PRIORITY_ID)
CREATE INDEX IX_CALL ON [CALL] (TASK_TEMPLATE_ID, CALLREASON_ID, CALLRESULT_ID, CALLTYPE_ID, CONTACT_ID, LEAD_ID, RELATED_DEAL, RELATED_ACCOUNT, RELATED_CAMPAIGN, CallOwner)
CREATE INDEX IX_MEETING ON [MEETING] (TASK_TEMPLATE_ID, Host) 
CREATE INDEX IX_MEETING_PARTICIPANT ON [MEETING_PARTICIPANT] (MEETING_ID, LEAD_ID, USER_ID, CONTACT_ID)
go